2025-03-20 08:03:50,441 - ERROR - Error occurred: 'list' object has no attribute 'to'
Traceback (most recent call last):
  File "e:\Python\DL\GFA2\src\main.py", line 98, in main
    batch = batch.to(device, non_blocking=True)
            ^^^^^^^^
AttributeError: 'list' object has no attribute 'to'
